#ifndef FILENAME_H_INCLUDED
#define FILENAME_H_INCLUDED

#define CONFIG_SUFFIX ".INI"
#define CONFIG_FILENAME "QUASI88"
#define KEYCONF_FILENAME "KEYCONF"
#define STATE_SUFFIX ".STA"
#define STATE_FILENAME "QUASI88"
#define SNAPSHOT_FILENAME "SAVE"
#define WAVEOUT_FILENAME "WAVE"

#endif
